name: vic
version: 0.1.0.0
github: "githubuser/vic"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/vic#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec >= 3.1.16.1
  - regex-compat >= 0.95.2.1
  - array >= 0.5.6.0
  - containers >= 0.6.7
  - range >= 0.3.0.2
  - criterion >= 1.6.3.0
  - pretty-simple >= 4.1.2.0
  - HUnit >= 1.6.2.0
  - search-algorithms >= 0.3.2
  - bifunctors >= 5.6.2
  - lens >= 5.2.3
  - MemoTrie >= 0.6.11
  - vector >= 0.13.1.0
  - transformers >= 0.6.1.0
  - unordered-containers >= 0.2.20
  - hashable >= 1.4.4.0
  - linear >= 1.16.2
  - mtl >= 2.3.1
  - list-t >= 1.0.5.7

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-unused-do-bind
  - -Wno-missing-signatures
  - -Wno-type-defaults
  - -Wno-unused-imports

library:
  source-dirs: src

executables:
  vic-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vic

tests:
  vic-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vic
